/* eslint-disable @typescript-eslint/no-explicit-any */
interface config {
  BASE_URL: any;
  CREATE_ADMIN: any;
  LOGIN_ADMIN: any;
  GET_ALL_USERS:any;
  GET_ADMIN_PROFILE:any;
  DELETE_ADMIN_USER:any;
  TOGGLE_ADMIN_USER:any;
  EDIT_ADMIN_USER:any;
  GET_ALL_WAVES_ADMIN:any;
  CREATE_USER: any;
  LOGIN_USER: any;
  GET_USER_NAME: any;
  GET_USER_DETAILS:any;
  CHANGE_PASSWORD: any;
  UPDATE_PREFERENCES: any;
  GET_PREFERENCES: any;
  UPDATE_PROFILE: any;
  ADMIN_DELETE_WAVE: any;
  GET_PERSONAL_DETAILS:any;
  UPDATE_PERSONAL_DETAILS:any;
  GET_BASIC_DETAILS: any;
  UPDATE_BASIC_DETAILS: any;
  CREATE_WAVE: any;
  GET_WAVE_LIST: any;
  UPDATE_WAVE_STATUTS: any;
  GET_ALL_WAVE_LIST: any;
  INVITE_FRIEND:any;
  ACCEPTED_FRIEND:any;
  ACCEPTED_FRIEND_LIST:any;
  SINGLE_USER_DETAILS:any;
}

export const Local: config = {
  BASE_URL: import.meta.env.VITE_BASE_URL,
  CREATE_ADMIN: import.meta.env.VITE_CREATE_ADMIN,
  LOGIN_ADMIN: import.meta.env.VITE_LOGIN_ADMIN,
  GET_ALL_USERS: import.meta.env.VITE_GET_ALL_USERS,
  GET_ADMIN_PROFILE: import.meta.env.VITE_GET_ADMIN_PROFILE,
  DELETE_ADMIN_USER: import.meta.env.VITE_DELETE_ADMIN_USER,
  TOGGLE_ADMIN_USER: import.meta.env.VITE_TOGGLE_ADMIN_USER,
  EDIT_ADMIN_USER: import.meta.env.VITE_EDIT_ADMIN_USER,
  GET_ALL_WAVES_ADMIN: import.meta.env.VITE_GET_ALL_WAVES_ADMIN,
  CREATE_USER: import.meta.env.VITE_CREATE_USER,
  LOGIN_USER: import.meta.env.VITE_LOGIN_USER,
  GET_USER_NAME: import.meta.env.VITE_GET_USER_NAME,
  GET_USER_DETAILS: import.meta.env.VITE_GET_USER_DETAILS,
  CHANGE_PASSWORD: import.meta.env.VITE_CHANGE_PASSWORD,
  UPDATE_PREFERENCES: import.meta.env.VITE_UPDATE_PREFERENCES,
  GET_PREFERENCES: import.meta.env.VITE_GET_PREFERENCES,
  UPDATE_PROFILE: import.meta.env.VITE_UPDATE_PROFILE,
  GET_PERSONAL_DETAILS: import.meta.env.VITE_GET_PERSONAL_DETAILS,
  UPDATE_PERSONAL_DETAILS: import.meta.env.VITE_UPDATE_PERSONAL_DETAILS,
  GET_BASIC_DETAILS: import.meta.env.VITE_GET_BASIC_DETAILS,
  UPDATE_BASIC_DETAILS: import.meta.env.VITE_UPDATE_BASIC_DETAILS,
  CREATE_WAVE: import.meta.env.VITE_CREATE_WAVE,
  ADMIN_DELETE_WAVE: import.meta.env.VITE_ADMIN_DELETE_WAVE,
  GET_WAVE_LIST: import.meta.env.VITE_GET_WAVE_LIST,
  UPDATE_WAVE_STATUTS: import.meta.env.VITE_UPDATE_WAVE_STATUS,
  GET_ALL_WAVE_LIST: import.meta.env.VITE_GET_ALL_WAVE_LIST,
  INVITE_FRIEND: import.meta.env.VITE_INVITE_FRIEND,
  ACCEPTED_FRIEND: import.meta.env.VITE_ACCEPTED_FRIEND_LIST,
  ACCEPTED_FRIEND_LIST: import.meta.env.VITE_ACCEPTED_FRIEND_LIST,
  SINGLE_USER_DETAILS: import.meta.env.VITE_GET_SINGLE_USER_DETAILS,
};
